### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by sygys** [ee02217/homeassistant-mi-heater#11]
I keep getting loads of errors from my heater. Get_prop is giving loads of errors also update errors randomly.

Also i see home assistant slowdowns when the heater is active. Things like scrolling through files with the file editor sometimes take several seconds to respond. This only seems to happen when i plugin the heater. So my guess is that the integration is causing serious problems in the background.

Im using the ZB1
![Knipsel](https://user-images.githubusercontent.com/73538763/127284545-8452a1cc-c182-4561-83c1-b17bdbb33e75.JPG)

**Comment by sygys** [comment]
How can this have 11 occurences in less then a second? No wonder Home assistant is freezing up when this error occurs
![Knipsel](https://user-images.githubusercontent.com/73538763/127305716-994f91c1-58d8-4ebc-9d7e-26840e5d84c4.JPG)

**Comment by jonicunha** [comment]
Hi,

I'm having the same issues with zhimi.heater.zb1

`Logger: custom_components.miheater.climate
Source: custom_components/miheater/climate.py:190
Integration: miheater
First occurred: 3:47:12 PM (2 occurrences)
Last logged: 5:07:12 PM

Fail to get_prop from Xiaomi heater
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 190, in getAttrData
    current_temperature=self._device.raw_command('get_properties', [{"siid":5,"piid":8}])
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 197, in raw_command
    return self.send(command, parameters)
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.22`

`Logger: homeassistant.helpers.entity
Source: custom_components/miheater/climate.py:203
Integration: miheater (documentation)
First occurred: 3:47:12 PM (2 occurrences)
Last logged: 5:07:12 PM

Update for climate.zhimi_heater_zb1_54_48_e6_6e_3c_51 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 190, in getAttrData
    current_temperature=self._device.raw_command('get_properties', [{"siid":5,"piid":8}])
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 197, in raw_command
    return self.send(command, parameters)
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.22

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/config/custom_components/miheater/climate.py", line 273, in async_update
    self.getAttrData()
  File "/config/custom_components/miheater/climate.py", line 203, in getAttrData
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady: None
`

This happens constantly, can you verify please?
Thanks!

**Comment by H0nzik1** [comment]
I have same error:


Logger: custom_components.miheater.climate
Source: custom_components/miheater/climate.py:71
Integration: miheater (documentation)
First occurred: 22:36:12 (3 occurrences)
Last logged: 22:37:35
Fail to setup Xiaomi heater

Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 71, in setup_platform
    device_info = device.info()
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 133, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 97, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.206
