### ISSUE TITLE
configuration invalid error

### ISSUE THREAD

**Issue by robertomontinaro80** [ee02217/homeassistant-mi-heater#17]
Hi all, I have home assistant core installed on my respberry. I've successfully added repository of mi-heater in HACS and installed it. Then I rebooted my HA. Actually I see the folder miheater created in custom_components folder, but when I add this lines:

climate:
  - platform: miheater
    host: <your device ip address>
    token: <your device miio token>
    name: xiaomi_heater
    model: zhimi.heater.mc2

in my configuration.yaml, I can't restart my HA because the configuration file seems to have errors. Below the logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:170
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:51:50 PM (3 occurrences)
Last logged: 10:52:38 PM

[2918542496] The system cannot restart because the configuration is not valid: Platform error climate.miheater - No module named 'miio'
[2918542496] The system cannot restart because the configuration is not valid: Platform error sensor.miheater - No module named 'custom_components.miheater.sensor'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homeassistant/__init__.py", line 170, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.miheater - No module named 'miio'

Please help me.

**Comment by robertomontinaro80** [comment]
@ee02217 please help me :(

**Comment by robertomontinaro80** [comment]
Nei guys just solved. I installed the integration. Restarted. Modified the configuration.yaml file adding the climate section and suddenly rebooted homeassistant without checking configuration.yaml file from UI interface. I rebooted HA from SSH. After reboot I was able to see the mi heater  integration available to be added to dashboard.
