### ISSUE TITLE
Deprecated constant

### ISSUE THREAD

**Issue by pollinolas** [ee02217/homeassistant-mi-heater#24]
since 2024.1.0 home assistant version I get these alerts:

HVAC_MODE_HEAT was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'miheater' custom integration
HVAC_MODE_COOL was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'miheater' custom integration
HVAC_MODE_OFF was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'miheater' custom integration
SUPPORT_TARGET_TEMPERATURE was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'miheater' custom integration
SUPPORT_FAN_MODE was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'miheater' custom integration
TEMP_CELSIUS was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'miheater' custom integration

**Comment by pollinolas** [comment]
@rapejim
Sorry for quoting you, but since it seems that this is abandoned by the author and right now I am using your fork...
Registrador: homeassistant.components.climate
Fuente: helpers/entity_platform.py:356
integración: Climatización (documentación, problemas)
Ocurrió por primera vez: 20:50:28 (1 ocurrencias)
Último inicio de sesión: 20:50:28

Error while setting up miheater platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miheater/climate.py", line 104, in setup_platform
    hass.services.async_register(DOMAIN, SERVICE_SET_ROOM_TEMP,
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'miheater' calls async_register from a thread at custom_components/miheater/climate.py, line 104: hass.services.async_register(DOMAIN, SERVICE_SET_ROOM_TEMP,. Please report it to the author of the 'miheater' custom integration.

**Comment by rapejim** [comment]
@pollinolas What is your model? (Or your config on configuration.yml)

**Comment by pollinolas** [comment]
> @pollinolas What is your model? (Or your config on configuration.yml) And version of your Home Assistant.
> 
> I am using it with Home Assistant 2024.4.4 (and now 2024.5.1) and zhimi.heater.mc2a (declared as mc2 in configuration.yml) without errors on logs, 🤔
I´m on 2024.5.1 and same model like you,i think so
  - platform: miheater
    host: 192.168.1.41
    token: **********
    name: Radiador Xiaomi
    model: zhimi.heater.mc2
It gives that error but the integration works, greetings

**Comment by rapejim** [comment]
> ... RuntimeError: Detected that custom integration 'miheater' calls async_register from a thread at custom_components/miheater/climate.py, line 104: hass.services.async_register(DOMAIN, SERVICE_SET_ROOM_TEMP, ...

@pollinolas Error fixed with new release of my fork [1.6.5](https://github.com/rapejim/homeassistant-mi-heater/releases/tag/1.6.5) if you are using my repo, you can update to solve this error.

**Comment by pollinolas** [comment]
everything correct, thanks for the support
