### ISSUE TITLE
Unable to add zhimi.heater.mc2

### ISSUE THREAD

**Issue by brsnik** [ee02217/homeassistant-mi-heater#34]
```
climate:
  - platform: miheater
    host: 10.6.61.13
    token: c5...19
    name: xiaomi_heater
    model: zhimi.heater.mc2
```

---

Error:

2024-12-12 19:26:27.429 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-12 19:26:27.430 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration miheater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-12 19:26:31.985 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'miheater' custom integration
2024-12-12 19:26:31.987 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'miheater' custom integration
2024-12-12 19:26:31.989 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'miheater' custom integration
2024-12-12 19:26:31.991 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'miheater' custom integration
2024-12-12 19:26:31.993 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'miheater' custom integration
2024-12-12 19:26:31.994 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from miheater, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'miheater' custom integration
2024-12-12 19:26:37.459 ERROR (SyncWorker_5) [custom_components.miheater.climate] Fail to setup Xiaomi heater
Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 72, in setup_platform
    device_info = device.info()
  File "/usr/local/lib/python3.13/site-packages/miio/click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 148, in info
    return self._fetch_info()
           ~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
                         ~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.6.61.13
2024-12-12 19:26:37.470 WARNING (MainThread) [homeassistant.components.climate] Platform miheater not ready yet: None; Retrying in background in 30 seconds
2024-12-12 19:26:42.347 WARNING (MainThread) [homeassistant.components.roborock.coordinator] Using the cloud API for device 46KlCS5JgyaqEolaqQF0td. This is not recommended as it can lead to rate limiting. We recommend making your vacuum accessible by your Home Assistant instance
2024-12-12 19:26:51.828 ERROR (SyncWorker_2) [custom_components.miheater.climate] Fail to setup Xiaomi heater
Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 72, in setup_platform
    device_info = device.info()
  File "/usr/local/lib/python3.13/site-packages/miio/click_common.py", line 183, in _wrap
    self._fetch_info()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
                         ~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.6.61.13
2024-12-12 19:27:56.837 ERROR (SyncWorker_2) [custom_components.miheater.climate] Fail to setup Xiaomi heater
Traceback (most recent call last):
  File "/config/custom_components/miheater/climate.py", line 72, in setup_platform
    device_info = device.info()
  File "/usr/local/lib/python3.13/site-packages/miio/click_common.py", line 183, in _wrap
    self._fetch_info()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
                         ~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.6.61.13

**Comment by bartonu4** [comment]
same

**Comment by rapejim** [comment]
I do a fork for my mc2a and it's compatible with mc2 too. If you want try it...
https://github.com/rapejim/homeassistant-mi-heater
