### ISSUE TITLE
Not work on zhimi.heater.za2

### ISSUE THREAD

**Issue by ChristianSwift** [ee02217/homeassistant-mi-heater#4]
**2020-12-20 15:01:01 ERROR (SyncWorker_4) [custom_components.miheater.climate] Fail to setup Xiaomi heater
Traceback (most recent call last):**
File "/config/custom_components/miheater/climate.py", line 68, in setup_platform
device_info = device.info()
File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 177, in info
return DeviceInfo(self.send("miIO.info"))
File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 143, in send
return self._protocol.send(
File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 160, in send
self.send_handshake()
File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 87, in send_handshake
raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.4.0.157
**2020-12-20 15:01:01 WARNING (MainThread) [homeassistant.components.climate] Platform miheater not ready yet. Retrying in 30 seconds.
2020-12-20 15:01:32 WARNING (SyncWorker_3) [custom_components.miheater.climate] zhimi.heater.za2 2.1.3 esp32 detected**

**Comment by ee02217** [comment]
Unfortunately that version seems to have some problem with the integration.
For now there is nothing I can do as I dont have that version.

If someone can get miio raw commands that work with that version I can update this integration.
To use raw commands see: https://github.com/rytilahti/python-miio

**Comment by ProZielinski** [comment]
I'm waiting for a revised version. the same problem
